---
- name: Bootstrap Rails Production Server
  hosts: web_servers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install basic packages
      apt:
        name:
          - git
          - curl
          - nginx
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - nodejs
          - npm
          - acl
          - gawk
          - libreadline6-dev
          - libyaml-dev
          - libsqlite3-dev
          - sqlite3
          - autoconf
          - libgdbm-dev
          - libncurses5-dev
          - automake
          - libtool
          - bison
          - pkg-config
          - libffi-dev
          - python3-psycopg2
        state: present

    # RVM Installation Logic
    - name: Import RVM GPG keys
      shell: gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
      args:
        creates: /home/ubuntu/.gnupg/pubring.kbx
      become_user: ubuntu

    - name: Install RVM
      shell: curl -sSL https://get.rvm.io | bash -s stable
      args:
        creates: /home/ubuntu/.rvm/bin/rvm
      become_user: ubuntu

    - name: Install Ruby 3.3.4 via RVM
      shell: /home/ubuntu/.rvm/bin/rvm install 3.3.4 --default
      args:
        creates: /home/ubuntu/.rvm/rubies/ruby-3.3.4
      become_user: ubuntu

    - name: Create application directory
      file:
        path: /home/ubuntu/hello-world-infra-lab
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Create PostgreSQL user
      become: yes
      become_user: postgres
      postgresql_user:
        name: hello_world
        password: "hello_world_123"
        role_attr_flags: NOSUPERUSER,CREATEDB

    - name: Create PostgreSQL database
      become: yes
      become_user: postgres
      postgresql_db:
        name: hello_world_production
        owner: hello_world

    - name: Configure PostgreSQL for MD5 authentication
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        regexp: '^local\s+all\s+all\s+peer'
        line: 'local   all             all                                     md5'
        backrefs: yes
      notify: Restart Postgres

    - name: Clone the repository
      git:
        repo: 'https://github.com/Sankalp555/hello-world-infra-lab.git'
        dest: /home/ubuntu/hello-world-infra-lab
        version: main
        force: yes
      become_user: ubuntu

    - name: Create .env.production file
      copy:
        content: |
          HELLO_WORLD_DATABASE_PASSWORD="hello_world_123"
          RAILS_ENV="production"
          RAILS_SERVE_STATIC_FILES="true"
          SECRET_KEY_BASE="489eeb8eee1b0292460448f56c54fbc5771a076caf19de1bf91ab7d4d93d1460788cf8029573b2d64b39ea0866b1026e906de222e97dd866ea4230ec1d6a4adf"
        dest: /home/ubuntu/hello-world-infra-lab/.env.production
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Setup Nginx reverse proxy
      copy:
        content: |
          server {
              listen 80;
              server_name _;
              location / {
                  proxy_pass http://localhost:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Create Systemd service for Rails
      copy:
        content: |
          [Unit]
          Description=Rails Hello World Production Lab
          After=network.target postgresql.service

          [Service]
          Type=simple
          User=ubuntu
          Group=ubuntu
          WorkingDirectory=/home/ubuntu/hello-world-infra-lab
          Environment="HELLO_WORLD_DATABASE_PASSWORD=hello_world_123"
          Environment="RAILS_ENV=production"
          Environment="RAILS_SERVE_STATIC_FILES=true"
          Environment="SECRET_KEY_BASE=489eeb8eee1b0292460448f56c54fbc5771a076caf19de1bf91ab7d4d93d1460788cf8029573b2d64b39ea0866b1026e906de222e97dd866ea4230ec1d6a4adf"
          ExecStart=/home/ubuntu/.rvm/bin/rvm 3.3.4 do bundle exec puma -C config/puma.rb
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/hello-world.service
      notify: Restart Rails

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart Rails
      systemd:
        name: hello-world
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Restart Postgres
      service:
        name: postgresql
        state: restarted
